# datasets.yml — 候选数据集清单
candidates:
  - name: Arcene
    openml_task_id: 168851
    task: classification
    target_name: "class"  # 对应数据里标签列的列名
  - name: Sonar
    openml_task_id: 39
    task: classification
    target_name: "Class"
