dataset: /Users/orion/Documents/td/engisynth-ai/engisynth/data/dataset-uci.csv
target: null
feature_types:
  Gallstone Status: categorical
  Age: numerical
  Gender: categorical
  Comorbidity: categorical
  Coronary Artery Disease (CAD): categorical
  Hypothyroidism: categorical
  Hyperlipidemia: categorical
  Diabetes Mellitus (DM): categorical
  Height: numerical
  Weight: numerical
  Body Mass Index (BMI): numerical
  Total Body Water (TBW): numerical
  Extracellular Water (ECW): numerical
  Intracellular Water (ICW): numerical
  Extracellular Fluid/Total Body Water (ECF/TBW): numerical
  Total Body Fat Ratio (TBFR) (%): numerical
  Lean Mass (LM) (%): numerical
  Body Protein Content (Protein) (%): numerical
  Visceral Fat Rating (VFR): numerical
  Bone Mass (BM): numerical
  Muscle Mass (MM): numerical
  Obesity (%): numerical
  Total Fat Content (TFC): numerical
  Visceral Fat Area (VFA): numerical
  Visceral Muscle Area (VMA) (Kg): numerical
  Hepatic Fat Accumulation (HFA): categorical
  Glucose: numerical
  Total Cholesterol (TC): numerical
  Low Density Lipoprotein (LDL): numerical
  High Density Lipoprotein (HDL): numerical
  Triglyceride: numerical
  Aspartat Aminotransferaz (AST): numerical
  Alanin Aminotransferaz (ALT): numerical
  Alkaline Phosphatase (ALP): numerical
  Creatinine: numerical
  Glomerular Filtration Rate (GFR): numerical
  C-Reactive Protein (CRP): numerical
  Hemoglobin (HGB): numerical
  Vitamin D: numerical
constraints:
- type: range
  cols:
  - Gallstone Status
  min: 0.0
  max: 1.0
- type: range
  cols:
  - Age
  min: 20.18
  max: 75.82
- type: range
  cols:
  - Gender
  min: 0.0
  max: 1.0
- type: range
  cols:
  - Comorbidity
  min: 0.0
  max: 1.0
- type: range
  cols:
  - Coronary Artery Disease (CAD)
  min: 0.0
  max: 1.0
- type: range
  cols:
  - Hypothyroidism
  min: 0.0
  max: 1.0
- type: range
  cols:
  - Hyperlipidemia
  min: 0.0
  max: 1.0
- type: range
  cols:
  - Diabetes Mellitus (DM)
  min: 0.0
  max: 1.0
- type: range
  cols:
  - Height
  min: 146.18
  max: 188.0
- type: range
  cols:
  - Weight
  min: 48.918
  max: 120.15
- type: range
  cols:
  - Body Mass Index (BMI)
  min: 18.636
  max: 45.202
- type: range
  cols:
  - Total Body Water (TBW)
  min: 27.018
  max: 57.31
- type: range
  cols:
  - Extracellular Water (ECW)
  min: 11.0
  max: 23.482
- type: range
  cols:
  - Intracellular Water (ICW)
  min: 14.836
  max: 34.428
- type: range
  cols:
  - Extracellular Fluid/Total Body Water (ECF/TBW)
  min: 34.1296
  max: 48.82
- type: range
  cols:
  - Total Body Fat Ratio (TBFR) (%)
  min: 11.318
  max: 46.601
- type: range
  cols:
  - Lean Mass (LM) (%)
  min: 53.3826
  max: 88.6574
- type: range
  cols:
  - Body Protein Content (Protein) (%)
  min: 9.7848
  max: 21.9038
- type: range
  cols:
  - Visceral Fat Rating (VFR)
  min: 1.0
  max: 20.0
- type: range
  cols:
  - Bone Mass (BM)
  min: 1.918
  max: 3.8
- type: range
  cols:
  - Muscle Mass (MM)
  min: 35.216
  max: 75.282
- type: range
  cols:
  - Obesity (%)
  min: 1.1
  max: 96.4518
- type: range
  cols:
  - Total Fat Content (TFC)
  min: 6.918
  max: 50.328
- type: range
  cols:
  - Visceral Fat Area (VFA)
  min: 2.481
  max: 28.7544
- type: range
  cols:
  - Visceral Muscle Area (VMA) (Kg)
  min: 20.508
  max: 40.264
- type: range
  cols:
  - Hepatic Fat Accumulation (HFA)
  min: 0.0
  max: 3.0
- type: range
  cols:
  - Glucose
  min: 79.18
  max: 317.62
- type: range
  cols:
  - Total Cholesterol (TC)
  min: 110.9
  max: 323.92
- type: range
  cols:
  - Low Density Lipoprotein (LDL)
  min: 41.98
  max: 223.46
- type: range
  cols:
  - High Density Lipoprotein (HDL)
  min: 26.0
  max: 85.28
- type: range
  cols:
  - Triglyceride
  min: 34.0
  max: 462.38
- type: range
  cols:
  - Aspartat Aminotransferaz (AST)
  min: 9.18
  max: 66.56
- type: range
  cols:
  - Alanin Aminotransferaz (ALT)
  min: 7.0
  max: 102.82
- type: range
  cols:
  - Alkaline Phosphatase (ALP)
  min: 16.62
  max: 143.2
- type: range
  cols:
  - Creatinine
  min: 0.5
  max: 1.2828
- type: range
  cols:
  - Glomerular Filtration Rate (GFR)
  min: 45.3708
  max: 128.2696
- type: range
  cols:
  - C-Reactive Protein (CRP)
  min: 0.0
  max: 29.83
- type: range
  cols:
  - Hemoglobin (HGB)
  min: 10.0
  max: 18.146
- type: range
  cols:
  - Vitamin D
  min: 4.918
  max: 46.738
generator:
  type: ctgan
  epochs: 300
  batch_size: 64
noise: {}
normalization: {}
