dataset: /Users/orion/Documents/td/engisynth-ai/engisynth/data/dataset-uci.csv
target: Gallstone Status
feature_types:
  Gallstone Status: categorical
  Age: numerical
  Gender: categorical
  Comorbidity: categorical
  Coronary Artery Disease (CAD): categorical
  Hypothyroidism: categorical
  Hyperlipidemia: categorical
  Diabetes Mellitus (DM): categorical
  Height: numerical
  Weight: numerical
  Body Mass Index (BMI): numerical
  Total Body Water (TBW): numerical
  Extracellular Water (ECW): numerical
  Intracellular Water (ICW): numerical
  Extracellular Fluid/Total Body Water (ECF/TBW): numerical
  Total Body Fat Ratio (TBFR) (%): numerical
  Lean Mass (LM) (%): numerical
  Body Protein Content (Protein) (%): numerical
  Visceral Fat Rating (VFR): numerical
  Bone Mass (BM): numerical
  Muscle Mass (MM): numerical
  Obesity (%): numerical
  Total Fat Content (TFC): numerical
  Visceral Fat Area (VFA): numerical
  Visceral Muscle Area (VMA) (Kg): numerical
  Hepatic Fat Accumulation (HFA): categorical
  Glucose: numerical
  Total Cholesterol (TC): numerical
  Low Density Lipoprotein (LDL): numerical
  High Density Lipoprotein (HDL): numerical
  Triglyceride: numerical
  Aspartat Aminotransferaz (AST): numerical
  Alanin Aminotransferaz (ALT): numerical
  Alkaline Phosphatase (ALP): numerical
  Creatinine: numerical
  Glomerular Filtration Rate (GFR): numerical
  C-Reactive Protein (CRP): numerical
  Hemoglobin (HGB): numerical
  Vitamin D: numerical
constraints: []
generator:
  type: ctgan
  epochs: 300
  batch_size: 60
noise: {}
normalization: {}
