# 改进后的硬件工程数据集配置
dataset: "hardware_test_data"
target: "performance_score"

# ===== 特征类型 =====
feature_types:
  # 来料参数
  material_density: numerical
  material_purity: numerical
  supplier_id: categorical

  # 制造参数
  temperature: numerical
  pressure: numerical
  duration: numerical
  cooling_rate: numerical

  # 能量分布（守恒约束）
  energy_heat: numerical
  energy_kinetic: numerical
  energy_potential: numerical

# ===== 约束定义 =====
constraints:
  # 能量守恒
  - type: sum_equal
    cols: [energy_heat, energy_kinetic, energy_potential]
    value: 100.0
    tol: 0.01          # ≤0.01 误差

  # 温度范围
  - type: range
    cols: [temperature]
    min: 20.0
    max: 300.0

  # 压力范围
  - type: range
    cols: [pressure]
    min: 0.1
    max: 10.0

  # 材料纯度范围
  - type: range
    cols: [material_purity]
    min: 0.95
    max: 1.0

  # 温度与冷却速率应保持正相关（而非严格单调）
  - type: correlation
    cols: [temperature, cooling_rate]
    value: 0.5         # 经验正相关系数约 0.5
    tol: 0.10

## ===== 噪声配置（可选）=====
## ⚠️ 如需生效，请在数据生成逻辑里实际注入这些噪声
#noise:
#  temperature:
#    type: gaussian
#    std: 2.0
#    relative: false
#
#  pressure:
#    type: gaussian
#    std: 0.05
#    relative: false
#
#  material_purity:
#    type: uniform
#    scale: 0.002       # ±0.2 %
#    relative: true
#
#  performance_score:
#    type: gaussian
#    std: 0.5
#    relative: false

# ===== 归一化配置 =====
normalization:
  temperature:
    method: minmax

  pressure:
    method: log        # 无 offset，直接 log(x)

  material_density:
    method: zscore

  cooling_rate:
    method: minmax

  duration:
    method: log        # 长尾分布建议对数缩放

# ===== 生成器配置 =====
generator:
  type: constrained_ctgan
  epochs: 500
  batch_size: 32
  max_rejection_samples: 20000
