dataset: /Users/orion/Documents/td/engisynth-ai/engisynth/data/secondary_data_sample.csv
target: null
feature_types:
  ? class;cap-diameter;cap-shape;cap-surface;cap-color;does-bruise-or-bleed;gill-attachment;gill-spacing;gill-color;stem-height;stem-width;stem-root;stem-surface;stem-color;veil-type;veil-color;has-ring;ring-type;spore-print-color;habitat;season
  : categorical
constraints: []
generator:
  type: ctgan
  epochs: 300
  batch_size: 64
noise: {}
normalization: {}
